-- Tangy Sessions — account invitations and event-scoped volunteer access.
-- Run after 0029_private_media_realtime_jobs.sql. Reverse with
-- supabase/rollbacks/0030_invitations_and_volunteer_access.down.sql.
--
-- 1. ACCOUNT INVITATIONS. Console accounts (Super Admin, Admin / Manager,
--    Staff) are created only by invitation. The invitation fixes the role; the
--    recipient never chooses it. The role is granted when the owner of the
--    invited email address signs in and accepts — not when the invite is sent
--    (admin-invite-user used to set the role immediately).
--      * token: 32 random bytes generated by the admin-invite-user Edge
--        Function; only its SHA-256 hash is stored here.
--      * expires after 72 hours, single use, revocable; creating a new
--        invitation for the same email revokes the previous open one.
--      * who may invite: Super Admin / Admin need `roles.manage` (never
--        delegable — see set_role_permission in 0018); Staff need `staff.invite`
--        (Super Admin and Admin / Manager by default, editable in the
--        permission matrix) or `users.manage`.
--
-- 2. SECURITY FIX — is_assigned_to_event() counted every event assignment, so
--    a staff account placed on an event as a volunteer/crew member got staff
--    access to that event's attendees, and partners (vendor, crew, volunteer)
--    could call admin RPCs such as event_health(). It now counts only staff
--    assignments. Partners keep reading their events through
--    event_member_kind() ("events: members read", 0018).
--
-- 3. SECURITY FIX — crew_applications accepted any status/review fields on
--    insert (the policy only checked user_id), so an applicant could file an
--    already-"approved" application and unlock the volunteer portal UI. New
--    applications from end users now always start as pending and unreviewed.
--
-- 4. EVENT-SCOPED VOLUNTEER APPLICATIONS. A volunteer application may name a
--    session (crew_applications.event_id). Approval puts the applicant on that
--    session's team as a volunteer (event_assignments). A member account still
--    becomes a Volunteer; a Staff account keeps its staff role — volunteering
--    never changes a console role and never adds console permissions. Staff
--    must name the session they want to volunteer at.

-- ===========================================================================
-- 1. ACCOUNT INVITATIONS
-- ===========================================================================

insert into role_permissions (role, permission) values
  ('super_admin', 'staff.invite'), ('admin', 'staff.invite')
on conflict do nothing;

create table if not exists account_invitations (
  id uuid primary key default gen_random_uuid(),
  email text not null check (email = lower(btrim(email)) and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' and length(email) <= 254),
  full_name text check (full_name is null or length(full_name) <= 120),
  role user_role not null check (role in ('super_admin', 'admin', 'staff')),
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references auth.users(id) on delete set null,
  revoked_at timestamptz,
  revoked_by uuid references auth.users(id) on delete set null,
  email_status text not null default 'pending' check (email_status in ('pending', 'sent', 'failed', 'not_configured')),
  check (expires_at > created_at),
  check (accepted_at is null or revoked_at is null)
);

-- At most one open invitation per email address.
create unique index if not exists account_invitations_one_open
  on account_invitations (email) where accepted_at is null and revoked_at is null;
create index if not exists account_invitations_created_idx on account_invitations (created_at desc);

-- No policies: rows (and token hashes) are reachable only through the
-- functions below.
alter table account_invitations enable row level security;
revoke all on account_invitations from anon, authenticated;

create or replace function console_role_rank(p_role user_role)
returns int
language sql immutable
as $$
  select case p_role when 'super_admin' then 3 when 'admin' then 2 when 'staff' then 1 else 0 end;
$$;

create or replace function can_invite_role(p_role user_role)
returns boolean
language sql stable security definer set search_path = public
as $$
  select case
    when p_role in ('super_admin', 'admin') then has_permission('roles.manage')
    when p_role = 'staff' then has_permission('staff.invite') or has_permission('users.manage')
    else false
  end;
$$;

create or replace function invitation_state(i account_invitations)
returns text
language sql stable
as $$
  select case
    when i.accepted_at is not null then 'accepted'
    when i.revoked_at is not null then 'revoked'
    when i.expires_at <= now() then 'expired'
    else 'pending'
  end;
$$;

-- Called by the admin-invite-user Edge Function with the inviter's own JWT.
create or replace function create_account_invitation(p_email text, p_full_name text, p_role user_role, p_token_hash text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_name text := nullif(btrim(coalesce(p_full_name, '')), '');
  v_profile profiles%rowtype;
  v_inv account_invitations%rowtype;
begin
  if p_role not in ('super_admin', 'admin', 'staff') then
    raise exception 'Invitations are for Super Admin, Admin / Manager and Staff accounts.';
  end if;
  if not can_invite_role(p_role) then
    raise exception 'You do not have permission to invite this role.' using errcode = '42501';
  end if;
  if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or length(v_email) > 254 then
    raise exception 'Enter a valid email address.';
  end if;
  if v_name is null or length(v_name) > 120 then
    raise exception 'Full name is required (120 characters at most).';
  end if;
  if coalesce(p_token_hash, '') !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid invitation token.';
  end if;

  select * into v_profile from profiles where lower(email) = v_email;
  if v_profile.id = auth.uid() then
    raise exception 'You cannot invite yourself.';
  end if;
  if v_profile.id is not null and not v_profile.is_active then
    raise exception 'That account is deactivated — reactivate it from Users & roles first.';
  end if;
  if v_profile.id is not null and console_role_rank(v_profile.role) >= console_role_rank(p_role) then
    raise exception 'That account already has % access or higher.', p_role;
  end if;

  -- A new invitation replaces any earlier open one for the same address.
  update account_invitations set revoked_at = now(), revoked_by = auth.uid()
    where email = v_email and accepted_at is null and revoked_at is null;

  insert into account_invitations (email, full_name, role, token_hash, invited_by, expires_at)
  values (v_email, v_name, p_role, p_token_hash, auth.uid(), now() + interval '72 hours')
  returning * into v_inv;

  perform audit_write('user.invited', 'invitation', v_inv.id::text,
    jsonb_build_object('email', v_email, 'role', p_role, 'existing_account', v_profile.id is not null,
      'expires_at', v_inv.expires_at));
  return jsonb_build_object('id', v_inv.id, 'expires_at', v_inv.expires_at, 'existing_account', v_profile.id is not null);
end;
$$;

-- The Edge Function records whether the email actually went out.
create or replace function set_invitation_email_status(p_id uuid, p_status text)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if p_status not in ('sent', 'failed', 'not_configured') then
    raise exception 'Invalid email status.';
  end if;
  update account_invitations set email_status = p_status
    where id = p_id and invited_by = auth.uid() and accepted_at is null and revoked_at is null;
end;
$$;

create or replace function revoke_account_invitation(p_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_inv account_invitations%rowtype;
begin
  select * into v_inv from account_invitations where id = p_id for update;
  if v_inv.id is null then
    raise exception 'Invitation not found.';
  end if;
  if not can_invite_role(v_inv.role) then
    raise exception 'You do not have permission to manage this invitation.' using errcode = '42501';
  end if;
  if invitation_state(v_inv) <> 'pending' then
    raise exception 'This invitation is already %.', invitation_state(v_inv);
  end if;
  update account_invitations set revoked_at = now(), revoked_by = auth.uid() where id = p_id;
  perform audit_write('user.invitation_revoked', 'invitation', p_id::text,
    jsonb_build_object('email', v_inv.email, 'role', v_inv.role));
end;
$$;

-- Console list (never returns token hashes).
create or replace function list_account_invitations(p_limit int default 50)
returns table (id uuid, email text, full_name text, role user_role, state text, email_status text,
  invited_by_name text, created_at timestamptz, expires_at timestamptz, accepted_at timestamptz, revoked_at timestamptz,
  can_manage boolean)
language plpgsql stable security definer set search_path = public
as $$
begin
  if not (has_permission('users.view') or has_permission('staff.invite')) then
    raise exception 'You do not have permission to view invitations.' using errcode = '42501';
  end if;
  return query
    select i.id, i.email, i.full_name, i.role, invitation_state(i), i.email_status,
      coalesce(p.full_name, p.email), i.created_at, i.expires_at, i.accepted_at, i.revoked_at,
      can_invite_role(i.role)
    from account_invitations i left join profiles p on p.id = i.invited_by
    order by i.created_at desc
    limit least(greatest(coalesce(p_limit, 50), 1), 200);
end;
$$;

-- What the invitation page shows before sign-in. Holding the 256-bit token is
-- the proof of receipt, so the invited address is shown to its holder.
create or replace function invitation_preview(p_token text)
returns jsonb
language plpgsql stable security definer set search_path = public, extensions
as $$
declare
  v_inv account_invitations%rowtype;
begin
  if coalesce(p_token, '') !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('state', 'invalid');
  end if;
  select * into v_inv from account_invitations where token_hash = encode(digest(p_token, 'sha256'), 'hex');
  if v_inv.id is null then
    return jsonb_build_object('state', 'invalid');
  end if;
  return jsonb_build_object(
    'state', invitation_state(v_inv),
    'email', v_inv.email,
    'role', v_inv.role,
    'invited_by', (select coalesce(full_name, 'A Tangy Super Admin') from profiles where id = v_inv.invited_by),
    'expires_at', v_inv.expires_at);
end;
$$;

-- The recipient, signed in as the invited email address, accepts.
create or replace function accept_account_invitation(p_token text)
returns user_role
language plpgsql security definer set search_path = public, extensions
as $$
declare
  v_inv account_invitations%rowtype;
  v_profile profiles%rowtype;
  v_email text;
begin
  if auth.uid() is null then
    raise exception 'Sign in with the invited email address first.';
  end if;
  if coalesce(p_token, '') !~ '^[0-9a-f]{64}$' then
    raise exception 'This invitation link is not valid.';
  end if;
  select * into v_inv from account_invitations
    where token_hash = encode(digest(p_token, 'sha256'), 'hex') for update;
  if v_inv.id is null then
    raise exception 'This invitation link is not valid.';
  end if;
  if invitation_state(v_inv) <> 'pending' then
    raise exception 'This invitation has %.', case invitation_state(v_inv)
      when 'accepted' then 'already been used' when 'revoked' then 'been withdrawn' else 'expired' end;
  end if;

  select lower(email) into v_email from auth.users where id = auth.uid();
  if v_email is distinct from v_inv.email then
    raise exception 'This invitation is for a different email address.';
  end if;

  select * into v_profile from profiles where id = auth.uid() for update;
  if v_profile.id is null then
    raise exception 'Your account is still being set up — try again in a moment.';
  end if;
  if not v_profile.is_active then
    raise exception 'This account is deactivated.';
  end if;
  if console_role_rank(v_profile.role) >= console_role_rank(v_inv.role) then
    raise exception 'Your account already has this access or higher.';
  end if;

  -- accepted_at = now() is what lets the role guard allow this one self-update.
  update account_invitations set accepted_at = now(), accepted_by = auth.uid() where id = v_inv.id;
  update profiles set role = v_inv.role, full_name = coalesce(full_name, v_inv.full_name) where id = auth.uid();

  perform audit_write('user.invitation_accepted', 'user', auth.uid()::text,
    jsonb_build_object('invitation_id', v_inv.id, 'role', v_inv.role, 'from', v_profile.role, 'invited_by', v_inv.invited_by));
  return v_inv.role;
end;
$$;

-- Role guard (0018) + one exception: the invited account's own role change,
-- inside the same transaction that accepted a matching invitation.
create or replace function prevent_role_self_escalation()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  v_jwt_role text := coalesce(auth.role(), '');
begin
  if new.role is not distinct from old.role and new.is_active is not distinct from old.is_active then
    return new;
  end if;

  -- No end-user JWT: SQL editor / migrations / service role. This is the
  -- bootstrap path for the first super_admin.
  if v_jwt_role not in ('authenticated', 'anon') then
    return new;
  end if;

  if new.id = auth.uid()
     and new.is_active is not distinct from old.is_active
     and exists (select 1 from account_invitations
                 where accepted_by = new.id and role = new.role and accepted_at = now()) then
    return new;
  end if;

  if new.id = auth.uid() then
    raise exception 'You cannot change your own role or account status.';
  end if;

  -- Application approval provisioning: user -> partner/artist role only, by a reviewer.
  if new.is_active is not distinct from old.is_active
     and old.role = 'user'
     and new.role in ('vendor', 'sponsor', 'volunteer', 'crew', 'venue', 'artist')
     and has_permission('applications.review') then
    return new;
  end if;

  if not has_permission('roles.manage') then
    raise exception 'Only a super admin can change roles or account status.';
  end if;
  return new;
end;
$$;

revoke all on function create_account_invitation(text, text, user_role, text), set_invitation_email_status(uuid, text),
  revoke_account_invitation(uuid), list_account_invitations(int), accept_account_invitation(text), can_invite_role(user_role)
  from public, anon;
grant execute on function create_account_invitation(text, text, user_role, text), set_invitation_email_status(uuid, text),
  revoke_account_invitation(uuid), list_account_invitations(int), accept_account_invitation(text), can_invite_role(user_role)
  to authenticated;
revoke all on function invitation_preview(text) from public;
grant execute on function invitation_preview(text) to anon, authenticated;

-- ===========================================================================
-- 2. STAFF EVENT SCOPE COUNTS STAFF ASSIGNMENTS ONLY
-- ===========================================================================

create or replace function is_assigned_to_event(p_event_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select current_role_name() in ('staff', 'admin', 'super_admin') and exists (
    select 1 from event_assignments
    where event_id = p_event_id and assignee_id = auth.uid() and assignee_role = 'staff' and status <> 'declined'
  );
$$;

-- ===========================================================================
-- 3 + 4. VOLUNTEER APPLICATIONS
-- ===========================================================================

-- 0018's check + staff accounts may hold a volunteer place (their role and
-- console permissions are unchanged by it).
create or replace function validate_event_assignment()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  v_role user_role;
begin
  select role into v_role from profiles where id = new.assignee_id;
  if new.assignee_role = 'staff' and v_role not in ('staff', 'admin', 'super_admin') then
    raise exception 'Only staff/admin accounts can be assigned as event staff.';
  end if;
  if tg_op = 'INSERT' and new.assignee_role in ('sponsor', 'vendor', 'volunteer', 'crew')
     and v_role is distinct from new.assignee_role::user_role
     and not (new.assignee_role = 'volunteer' and v_role = 'staff') then
    raise exception 'This account is not an approved % (current role: %).', new.assignee_role, coalesce(v_role::text, 'none');
  end if;
  return new;
end;
$$;

alter table crew_applications add column if not exists event_id uuid references events(id) on delete set null;
create index if not exists crew_applications_event_id_idx on crew_applications (event_id);

create or replace function guard_crew_application_insert()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  v_event events%rowtype;
  v_role user_role;
begin
  -- SQL editor / service role (seeds, imports) are trusted.
  if coalesce(auth.role(), '') not in ('authenticated', 'anon') then
    return new;
  end if;

  new.status := 'pending';
  new.reviewed_by := null; new.reviewed_at := null; new.review_notes := null; new.decision_reason := null;

  select role into v_role from profiles where id = new.user_id;
  if new.event_id is null then
    if new.category = 'volunteer' and console_role_rank(v_role) > 0 then
      raise exception 'Choose the session you want to volunteer at.';
    end if;
    return new;
  end if;

  if new.category is distinct from 'volunteer' then
    raise exception 'Only volunteer applications are for a specific session.';
  end if;
  select * into v_event from events where id = new.event_id;
  if v_event.id is null or v_event.status not in ('on-sale', 'sold-out') or v_event.event_date < current_date then
    raise exception 'That session is not open for volunteers.';
  end if;
  if exists (select 1 from event_assignments where event_id = new.event_id and assignee_id = new.user_id
             and assignee_role = 'volunteer' and status <> 'declined') then
    raise exception 'DUPLICATE_APPLICATION: You are already on the volunteer team for this session.';
  end if;
  new.event_interest := v_event.name || ' · ' || to_char(v_event.event_date, 'DD Mon YYYY');
  return new;
end;
$$;

drop trigger if exists crew_applications_guard_insert on crew_applications;
create trigger crew_applications_guard_insert before insert on crew_applications
  for each row execute function guard_crew_application_insert();

-- 0025's duplicate guard: a volunteer application is per session.
create or replace function guard_duplicate_application()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  v_label text;
  v_dup boolean := false;
begin
  if new.user_id is null then
    return new;
  end if;
  -- Serialise this user's submissions so two quick clicks can't both pass.
  perform pg_advisory_xact_lock(hashtext('application:' || new.user_id::text));
  if tg_table_name = 'collaborations' then
    v_label := replace(new.type::text, '_', ' ');
    v_dup := exists (select 1 from collaborations where user_id = new.user_id and type = new.type and status = 'pending');
  elsif tg_table_name = 'crew_applications' then
    v_label := coalesce(new.category, 'crew') || case when new.event_id is not null then ' (this session)' else '' end;
    v_dup := exists (select 1 from crew_applications where user_id = new.user_id and category is not distinct from new.category
                     and event_id is not distinct from new.event_id and status = 'pending');
  elsif tg_table_name = 'artists' then
    v_label := 'artist';
    v_dup := exists (select 1 from artists where user_id = new.user_id and status = 'pending');
  elsif tg_table_name = 'private_enquiries' then
    v_label := 'private session';
    v_dup := exists (select 1 from private_enquiries where user_id = new.user_id and type = new.type and status = 'pending');
  elsif tg_table_name = 'contact_enquiries' then
    -- The same message twice within a day is a double submit, not a new enquiry.
    if exists (select 1 from contact_enquiries where user_id = new.user_id and created_at > now() - interval '24 hours'
               and lower(btrim(message)) = lower(btrim(new.message))) then
      raise exception 'DUPLICATE_APPLICATION: We already have this message — the team will reply soon.';
    end if;
    return new;
  end if;
  if v_dup then
    raise exception 'DUPLICATE_APPLICATION: You already have a pending % application — we''ll be in touch.', v_label;
  end if;
  return new;
end;
$$;

-- 0017's approval + the session place for volunteer applications that name one.
create or replace function approve_crew_application(p_id uuid, p_notes text default null)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_app crew_applications%rowtype;
  v_assigned boolean := false;
begin
  if not has_permission('applications.review') then
    raise exception 'You do not have permission to review applications.';
  end if;
  select * into v_app from crew_applications where id = p_id for update;
  if v_app.id is null then
    raise exception 'Application not found.';
  end if;
  if v_app.status <> 'pending' then
    raise exception 'This application has already been reviewed (%).', v_app.status;
  end if;

  update crew_applications
    set status = 'approved', reviewed_by = auth.uid(), reviewed_at = now(), review_notes = p_notes
    where id = p_id;

  if v_app.user_id is not null then
    if v_app.category = 'volunteer' then
      insert into volunteer_profiles (id) values (v_app.user_id) on conflict (id) do nothing;
      -- Members become Volunteers; console accounts keep their role.
      update profiles set role = 'volunteer' where id = v_app.user_id and role = 'user';
      if v_app.event_id is not null and not exists (
        select 1 from event_assignments where event_id = v_app.event_id and assignee_id = v_app.user_id
          and assignee_role = 'volunteer' and status <> 'declined') then
        insert into event_assignments (event_id, assignee_role, assignee_id, title, status, assigned_by)
        values (v_app.event_id, 'volunteer', v_app.user_id, 'Volunteer', 'confirmed', auth.uid());
        v_assigned := true;
      end if;
    else
      insert into crew_profiles (id) values (v_app.user_id) on conflict (id) do nothing;
      update profiles set role = 'crew' where id = v_app.user_id and role = 'user';
    end if;

    insert into application_notifications (source_table, source_id, notification_type)
    values ('crew_applications', p_id, 'approval')
    on conflict (source_table, source_id, notification_type) do nothing;
  end if;

  perform audit_write('application.approved', 'crew_application', p_id::text,
    jsonb_build_object('type', v_app.category, 'applicant', v_app.name, 'notes', p_notes,
      'role_provisioned', v_app.user_id is not null, 'event_id', v_app.event_id, 'event_team_place', v_assigned));
end;
$$;
