// DEMO-ONLY CODE — see src/config/demoAdmin.js for the deletion note.
//
// Synthetic, clearly-fake identities used ONLY to let the real dashboard
// components render outside of a real Supabase session. Every id below is a
// syntactically valid but obviously-reserved UUID — never generated by
// Supabase, never matching a real row, so every real query these
// dashboards make (bookings, assignments, applications...) safely returns
// zero rows. Nothing here is written to Supabase; these objects never leave
// the browser.
const demoUuid = (n) => `00000000-0000-0000-0000-00000000000${n}`;

export const DEMO_PROFILES = {
  patron: {
    id: demoUuid(1),
    full_name: 'Demo Patron',
    email: 'demo.patron@tangysessions.test',
    role: 'user',
    passport_id: 'DEMO-PATRON',
    member_since: new Date().toISOString(),
  },
  crew: {
    id: demoUuid(2),
    full_name: 'Demo Crew Member',
    email: 'demo.crew@tangysessions.test',
    role: 'crew',
  },
  volunteer: {
    id: demoUuid(3),
    full_name: 'Demo Volunteer',
    email: 'demo.volunteer@tangysessions.test',
    role: 'volunteer',
  },
  vendor: {
    id: demoUuid(4),
    full_name: 'Demo Vendor',
    email: 'demo.vendor@tangysessions.test',
    role: 'vendor',
  },
  sponsor: {
    id: demoUuid(5),
    full_name: 'Demo Sponsor',
    email: 'demo.sponsor@tangysessions.test',
    role: 'sponsor',
  },
  venue: {
    id: demoUuid(6),
    full_name: 'Demo Venue Partner',
    email: 'demo.venue@tangysessions.test',
    role: 'venue',
  },
};
